"""
Game Knowledge Base — Mission Control

All game knowledge is generated at runtime via the Dynamic Profile Engine:
  - When a game is detected, a background thread queries NVIDIA NIM for the
    game's default PC controls and gameplay tips.
  - If the user has changed keybindings in-game, the Config File Watcher
    parses those changes and patches the profile automatically.
  - User-defined overrides (from config) are merged on top of the
    auto-generated profile as the final layer.

No game-specific data is hardcoded here. Every game — known or unknown —
goes through the same fully automatic pipeline.
"""
import json
import logging
import os
import re
import threading
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

# GAME_DATA is intentionally empty — all profiles are built at runtime.
# Kept as a constant for backwards-compatibility with any import that
# checks `game_key in GAME_DATA`.
GAME_DATA: Dict[str, dict] = {}


# ─────────────────────────────────────────────────────────────────────────────
# Dynamic Profile Dataclass
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class DynamicGameProfile:
    """
    Holds the complete runtime-generated profile for a game.

    Sources (in order of application):
      1. ``llm``         — generated by NVIDIA NIM querying default PC controls
      2. ``config_file`` — parsed from the game's own settings/keybind file(s)
      3. ``user``        — user-defined overrides applied on top of layers 1+2
    """
    game_name: str
    game_key: str
    # Base keybinds discovered by LLM or config-file watcher
    keybinds: Dict[str, Dict[str, str]] = field(default_factory=dict)
    # Game tips generated by the LLM
    tips: List[str] = field(default_factory=list)
    generated_at: float = field(default_factory=time.time)
    # Which source populated keybinds ("llm" | "config_file" | "user")
    source: str = "llm"
    # Path of the config file that last updated this profile (if any)
    config_file_path: Optional[str] = None
    # User-defined overrides merged on top of keybinds when building context
    user_overrides: Dict[str, str] = field(default_factory=dict)


class GameKnowledgeBase:
    """
    Runtime game knowledge lookup.

    All knowledge is dynamic — there is no hardcoded game data.
    The pipeline is:
      1. Game detected  → identify_game() normalises the title to a stable key
      2. Background LLM → _generate_game_profile_bg() fetches default controls
      3. Config watcher → update_dynamic_profile() patches in-game changes
      4. User overrides → applied on top at context-build time
    """

    # How often to refresh a profile (seconds). LLM-generated data is stable,
    # so 1 hour is fine.  Config-file changes bypass this via the watcher.
    _PROFILE_REFRESH_INTERVAL = 3600.0
    # LLM call timeout (seconds)
    _LLM_TIMEOUT = 15.0
    # How long to wait before retrying after a failed fetch (5 minutes).
    # Prevents an infinite retry storm when the LLM endpoint is unreachable.
    _FETCH_RETRY_COOLDOWN = 300.0

    def __init__(self):
        self._active_game_key: Optional[str] = None
        self._active_game_name: str = ""  # human-readable title for the LLM prompt

        # Profile store: game_key → DynamicGameProfile
        self._dynamic_profiles: Dict[str, DynamicGameProfile] = {}
        self._profile_generation_lock = threading.Lock()
        # In-flight generation guard
        self._generating: set = set()
        # Failed fetch cooldown: game_key → timestamp of last failure
        self._failed_fetches: Dict[str, float] = {}
        # Lazy NIM client
        self._nim_client = None
        self._nim_model: Optional[str] = None

    # ── Key helpers ──────────────────────────────────────────────────────────

    def _make_game_key(self, game_name: str) -> str:
        """Derive a stable snake_case key from any game title."""
        return re.sub(r"[^a-z0-9]+", "_", game_name.lower()).strip("_")

    # ── NIM client acquisition ───────────────────────────────────────────────

    def _inject_nim_client(self, config: dict):
        """Lazily create the OpenAI client pointed at NVIDIA NIM."""
        if self._nim_client:
            return
        try:
            from openai import OpenAI
            agent_cfg = config.get("ai_agent", {})
            api_key = (
                agent_cfg.get("nvidia_api_key")
                or os.environ.get("NVIDIA_API_KEY")
                or os.environ.get("AI_GAMING_ASSISTANT_NVIDIA_API_KEY")
            )
            base_url = agent_cfg.get("endpoint_url") or os.environ.get(
                "NVIDIA_ENDPOINT_URL", "https://integrate.api.nvidia.com/v1"
            )
            invalid = {"YOUR_NVIDIA_API_KEY_HERE", "your_nvidia_api_key_here", "", None}
            if api_key and api_key.strip() not in invalid:
                self._nim_client = OpenAI(base_url=base_url, api_key=api_key)
                self._nim_model = (
                    agent_cfg.get("model_id") or "meta/llama-3.3-70b-instruct"
                )
                logger.info("[GameKB] NIM client ready for dynamic profile generation.")
        except Exception as e:
            logger.debug(f"[GameKB] NIM client init failed: {e}")

    # ── LLM profile generation ───────────────────────────────────────────────

    def _fetch_keybinds_via_llm(self, game_name: str) -> Optional[Dict]:
        """
        Ask the LLM for the default PC keyboard/mouse controls for `game_name`.

        Returns a dict ``{"keybinds": {...}, "tips": [...]}`` or None.
        The LLM is instructed to output **only** valid JSON so we can parse
        it reliably without any post-processing heuristics.
        """
        if not self._nim_client:
            return None

        prompt = (
            f"You are a comprehensive PC gaming encyclopedia.\n"
            f"Output ONLY a valid JSON object (no markdown, no explanation) "
            f"with the **default** PC keyboard and mouse controls for the game "
            f"'{game_name}'.\n\n"
            f"Required JSON schema:\n"
            f"{{\n"
            f'  "keybinds": {{\n'
            f'    "movement": {{"ActionName": "Key", ...}},\n'
            f'    "combat":   {{"ActionName": "Key", ...}},\n'
            f'    "vehicle":  {{"ActionName": "Key", ...}},\n'
            f'    "special":  {{"ActionName": "Key", ...}}\n'
            f"  }},\n"
            f'  "tips": ["tip1", "tip2", "tip3"]\n'
            f"}}\n\n"
            f"Rules:\n"
            f"- Include only the categories that exist in this game.\n"
            f"- Use concise key names: W, A, S, D, LMB, RMB, Space, Shift, "
            f"Ctrl, E, Tab, F, R, G, Q, etc.\n"
            f"- For combo keys use '+' (e.g. 'Shift+W').\n"
            f"- Return ONLY the JSON object, nothing else."
        )

        try:
            response = self._nim_client.chat.completions.create(
                model=self._nim_model or "meta/llama-3.3-70b-instruct",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.1,
                max_tokens=1200,
                timeout=self._LLM_TIMEOUT,
            )
            raw = response.choices[0].message.content.strip()
            # Strip markdown code fences in case the model adds them
            if raw.startswith("```"):
                raw = re.sub(r"^```[a-z]*\n?", "", raw)
                raw = re.sub(r"\n?```$", "", raw.strip())
            data = json.loads(raw)
            logger.info(
                f"[GameKB] LLM keybind profile generated for '{game_name}'."
            )
            return data
        except Exception as e:
            logger.warning(
                f"[GameKB] LLM keybind fetch failed for '{game_name}': {e}"
            )
            return None

    def _generate_game_profile_bg(self, game_name: str, config: dict):
        """
        Background thread entry point.
        Generates and caches a DynamicGameProfile for `game_name`.
        Guards against duplicate in-flight calls for the same key.
        Failed fetches are subject to a cooldown so the pipeline cannot
        cause an infinite retry storm on a dead/unreachable LLM endpoint.
        """
        game_key = self._make_game_key(game_name)

        with self._profile_generation_lock:
            if game_key in self._generating:
                return  # already in-flight
            existing = self._dynamic_profiles.get(game_key)
            if existing and (time.time() - existing.generated_at) < self._PROFILE_REFRESH_INTERVAL:
                return  # profile is still fresh
            # Respect the failed-fetch cooldown
            last_fail = self._failed_fetches.get(game_key, 0.0)
            if (time.time() - last_fail) < self._FETCH_RETRY_COOLDOWN:
                return  # still in cooldown after a previous failure
            self._generating.add(game_key)

        fetch_succeeded = False
        try:
            self._inject_nim_client(config)
            data = self._fetch_keybinds_via_llm(game_name)
            if data:
                profile = DynamicGameProfile(
                    game_name=game_name,
                    game_key=game_key,
                    keybinds=data.get("keybinds", {}),
                    tips=data.get("tips", []),
                    generated_at=time.time(),
                    source="llm",
                )
                with self._profile_generation_lock:
                    # Preserve any user overrides that existed before
                    old = self._dynamic_profiles.get(game_key)
                    if old:
                        profile.user_overrides = old.user_overrides
                    self._dynamic_profiles[game_key] = profile
                    # Clear any stale failure record on success
                    self._failed_fetches.pop(game_key, None)
                total = sum(
                    len(v) for v in profile.keybinds.values() if isinstance(v, dict)
                )
                logger.info(
                    f"[GameKB] Profile stored for '{game_name}' ({total} keybinds)."
                )
                fetch_succeeded = True
            else:
                logger.warning(
                    f"[GameKB] No LLM profile returned for '{game_name}'."
                )
        except Exception as e:
            logger.error(f"[GameKB] Profile generation error for '{game_name}': {e}")
        finally:
            with self._profile_generation_lock:
                self._generating.discard(game_key)
                if not fetch_succeeded:
                    # Record failure timestamp so we respect the retry cooldown
                    self._failed_fetches[game_key] = time.time()
                    logger.debug(
                        f"[GameKB] Fetch failed for '{game_name}' — "
                        f"will retry in {self._FETCH_RETRY_COOLDOWN:.0f}s."
                    )

    # ── Profile update API (called by ConfigWatcher and user-override layer) ─

    def update_dynamic_profile(
        self,
        game_key: str,
        keybinds: dict,
        source: str = "config_file",
        config_path: str = None,
    ):
        """
        Inject or patch a profile from an external source (config file watcher).

        If a profile already exists (e.g. from the LLM), the new keybinds are
        *merged on top* so neither source loses its data.
        User overrides are preserved.
        """
        with self._profile_generation_lock:
            existing = self._dynamic_profiles.get(game_key)

        if existing:
            # Merge: new keybinds take precedence over old within each category
            merged = {cat: dict(binds) for cat, binds in existing.keybinds.items()}
            for cat, binds in keybinds.items():
                merged.setdefault(cat, {}).update(binds)
            game_name = existing.game_name
            user_overrides = existing.user_overrides
        else:
            merged = {cat: dict(binds) for cat, binds in keybinds.items()}
            game_name = game_key.replace("_", " ").title()
            user_overrides = {}

        profile = DynamicGameProfile(
            game_name=game_name,
            game_key=game_key,
            keybinds=merged,
            tips=existing.tips if existing else [],
            generated_at=time.time(),
            source=source,
            config_file_path=config_path,
            user_overrides=user_overrides,
        )
        with self._profile_generation_lock:
            self._dynamic_profiles[game_key] = profile
        logger.info(
            f"[GameKB] Profile updated for '{game_name}' (source={source}, "
            f"total categories={len(merged)})."
        )

    def apply_user_overrides(self, game_key: str, overrides: Dict[str, str]):
        """
        Store user-defined keybind overrides for a game.
        These are applied as the final layer when building the context block
        or resolving voice macro keys — they never clobber the base profile.
        """
        with self._profile_generation_lock:
            existing = self._dynamic_profiles.get(game_key)

        if existing:
            existing.user_overrides.update(overrides)
            logger.info(
                f"[GameKB] User overrides applied for '{existing.game_name}': "
                f"{list(overrides.keys())}"
            )
        else:
            # Profile not yet generated — store overrides early; they'll be
            # picked up once the LLM profile arrives.
            placeholder = DynamicGameProfile(
                game_name=game_key.replace("_", " ").title(),
                game_key=game_key,
                user_overrides=overrides,
            )
            with self._profile_generation_lock:
                self._dynamic_profiles[game_key] = placeholder
            logger.info(
                f"[GameKB] User overrides stored (profile pending) for '{game_key}'."
            )

    def get_dynamic_profile(self, game_key: str) -> Optional[DynamicGameProfile]:
        """Return the profile for a game key, or None if not yet generated."""
        return self._dynamic_profiles.get(game_key)

    # ── Game detection ───────────────────────────────────────────────────────

    def identify_game(self, game_title: str, config: dict = None) -> Optional[str]:
        """
        Map a window/process title to a stable game key and trigger
        background profile generation if needed.
        """
        if game_title:
            for char in ['\u200b', '\u200c', '\u200d', '\ufeff', '\u200e', '\u200f']:
                game_title = game_title.replace(char, '')
        title_lower = (game_title or "").lower().strip()
        if not title_lower or title_lower in ("no game detected", "unknown"):
            return None

        resolved_key = self._make_game_key(game_title)
        canonical_name = game_title

        if self._active_game_key != resolved_key:
            logger.info(
                f"[GameKB] Active game → '{resolved_key}' (from title '{game_title}')"
            )
            self._active_game_key = resolved_key
            self._active_game_name = canonical_name

        # Trigger background LLM generation if profile is missing or stale
        existing = self._dynamic_profiles.get(resolved_key)
        needs_refresh = (
            existing is None
            or (time.time() - existing.generated_at) >= self._PROFILE_REFRESH_INTERVAL
        )
        if needs_refresh and config:
            # Don't spawn a thread if a previous attempt failed and the cooldown
            # hasn't expired yet — this prevents a retry storm at pipeline rate.
            last_fail = self._failed_fetches.get(resolved_key, 0.0)
            on_cooldown = (time.time() - last_fail) < self._FETCH_RETRY_COOLDOWN
            in_flight = resolved_key in self._generating
            if not on_cooldown and not in_flight:
                threading.Thread(
                    target=self._generate_game_profile_bg,
                    args=(self._active_game_name, config),
                    daemon=True,
                    name=f"GameKB-{resolved_key}",
                ).start()

        return resolved_key

    # ── Context builder ──────────────────────────────────────────────────────

    def build_context_block(
        self,
        game_key: Optional[str] = None,
        include_keybinds: bool = True,
    ) -> str:
        """
        Build a compact, voice-guide-ready context string for injection into
        NIM prompts.

        Layer order in output (lowest → highest, all visible to LLM):
          1. Base keybinds  (LLM-generated defaults)
          2. Config-file patches (in-game setting changes)
          3. User overrides (always shown last so the LLM knows the real keys)
        """
        key = game_key or self._active_game_key
        if not key:
            return ""

        profile = self._dynamic_profiles.get(key)

        if not profile:
            # Profile is in-flight — give the LLM a minimal breadcrumb
            name = self._active_game_name or key.replace("_", " ").title()
            return f"[GAME] {name} (keybind profile loading — generation in progress)"

        lines: List[str] = []
        lines.append(
            f"[GAME] {profile.game_name}  "
            f"[source: {profile.source}]"
        )

        if include_keybinds and profile.keybinds:
            # Flatten all categories; include user overrides as annotations
            kb_parts = []
            for category, bindings in profile.keybinds.items():
                if not isinstance(bindings, dict):
                    continue
                for action, key_str in bindings.items():
                    override = profile.user_overrides.get(action)
                    if override:
                        kb_parts.append(f"{action}: {override} (user-set)")
                    else:
                        kb_parts.append(f"{action}: {key_str}")
            if kb_parts:
                # Show up to 16 bindings; LLM can ask for more via tool call if needed
                lines.append("[KEYBINDS] " + " | ".join(kb_parts[:16]))
            if len(kb_parts) > 16:
                lines.append(f"  … and {len(kb_parts) - 16} more bindings.")

        if profile.tips:
            lines.append("[TIPS] " + " | ".join(profile.tips[:2]))

        return "\n".join(lines)

    # ── Action → key resolver (used by voice macro engine) ──────────────────

    def get_control_for_action(self, action: str) -> str:
        """
        Look up the effective keybind for an action (e.g. 'aim', 'reload').

        Applies the user-override layer on top of the base profile so the
        answer always reflects what the player has configured in-game.
        """
        key = self._active_game_key
        if not key:
            return ""

        profile = self._dynamic_profiles.get(key)
        if not profile:
            return ""

        action_lower = action.lower()

        # 1. User override wins
        for label, bind in profile.user_overrides.items():
            if action_lower in label.lower():
                return f"{label}: {bind} (user-configured)"

        # 2. Base profile (LLM / config-file)
        for bindings in profile.keybinds.values():
            if isinstance(bindings, dict):
                for label, bind in bindings.items():
                    if action_lower in label.lower():
                        return f"{label}: {bind}"

        return ""

    def query_knowledge(self, prompt: str, game_name: str, config: dict) -> dict:
        """
        Layer 1 Unified Interface: Queries RAG (local docs) and Web Search (wiki, patch notes) concurrently.
        Returns a dict with 'rag_context' and 'web_context'.
        """
        result = {"rag_context": "", "web_context": ""}
        
        from concurrent.futures import ThreadPoolExecutor, wait
        
        # Init RAG Engine lazily
        if not hasattr(self, "_rag_engine"):
            try:
                from ai_brain.rag_engine import GameRAGEngine
                base_dir = os.path.dirname(os.path.abspath(__file__))
                self._rag_engine = GameRAGEngine(
                    data_dir=os.path.join(base_dir, "rag_data"),
                    persist_dir=os.path.join(base_dir, "rag_index"),
                    nvidia_api_key=config.get("ai_agent", {}).get("nvidia_api_key")
                )
            except Exception as e:
                logger.error(f"Failed to initialize RAG Engine: {e}")
                self._rag_engine = None

        # Init Web Search Engine lazily
        if not hasattr(self, "_web_search"):
            try:
                from ai_brain.web_search import WebSearchEngine
                self._web_search = WebSearchEngine(config=config)
            except Exception as e:
                logger.error(f"Failed to initialize Web Search: {e}")
                self._web_search = None
                
        def run_rag():
            if self._rag_engine:
                try:
                    rag_res = self._rag_engine.query(prompt, k=4)
                    if rag_res and len(rag_res) > 20:
                        result["rag_context"] = f"\n[RAG Context (Local Docs)]:\n{rag_res}"
                except Exception as e:
                    logger.debug(f"RAG query failed: {e}")
                    
        def run_web():
            if self._web_search:
                try:
                    task = self._web_search.detect_task(prompt)
                    search_res = self._web_search.search(prompt, task=task, game_name=game_name)
                    if search_res and search_res.get("answer"):
                        result["web_context"] = f"\n[Live Web Context ({search_res.get('source', 'web')}, {task})]:\n{search_res['answer']}"
                except Exception as e:
                    logger.debug(f"Web query failed: {e}")

        executor = ThreadPoolExecutor(max_workers=2)
        futures = [executor.submit(run_rag), executor.submit(run_web)]
        wait(futures, timeout=8.0)
        executor.shutdown(wait=False)
        
        return result

    # ── Convenience accessors ────────────────────────────────────────────────

    def get_tips(self) -> List[str]:
        """Return gameplay tips for the active game."""
        key = self._active_game_key
        if not key:
            return []
        profile = self._dynamic_profiles.get(key)
        return profile.tips if profile else []

    @property
    def active_game(self) -> Optional[str]:
        return self._active_game_key

    @property
    def active_game_name(self) -> str:
        return self._active_game_name


# Module-level singleton
_kb_instance: Optional[GameKnowledgeBase] = None


def get_knowledge_base() -> GameKnowledgeBase:
    """Return the global GameKnowledgeBase singleton."""
    global _kb_instance
    if _kb_instance is None:
        _kb_instance = GameKnowledgeBase()
    return _kb_instance
