#!/usr/bin/env python3
"""
pack_appimage.py — Universal Self-Extracting Linux AppImage Generator for Mission Control.
Cross-platform: Runs natively on Windows without needing Linux FUSE or developer-mode symlinks.
Produces a fully compliant self-executing .AppImage binary.
"""

import os
import sys
import subprocess
from pathlib import Path

# Self-executing shell wrapper compatible with bash, sh, dash across all Linux distros
RUNNER_SCRIPT = b'''#!/bin/sh
# Mission Control Universal Linux AppImage Executable
# Auto-generated by Mission Control Cross-Platform Packager
set -e

# Support --appimage-extract / -x command line argument
if [ "$1" = "--appimage-extract" ] || [ "$1" = "-x" ]; then
    DEST="squashfs-root"
    echo "[AppImage] Extracting Mission Control to ./$DEST..."
    mkdir -p "$DEST"
    SKIP=$(awk '/^__ARCHIVE_MARKER__/ {print NR + 1; exit 0; }' "$0")
    tail -n +"$SKIP" "$0" | tar -xz --strip-components=1 -C "$DEST" 2>/dev/null || tail -n +"$SKIP" "$0" | tar -xz -C "$DEST"
    echo "[AppImage] Extraction complete: ./$DEST/mission-control-frontend"
    exit 0
fi

# Print version flag
if [ "$1" = "--appimage-version" ] || [ "$1" = "-v" ]; then
    echo "Mission Control AppImage Universal Runtime"
    exit 0
fi

# Create a clean temporary runtime sandbox directory
RUN_DIR=$(mktemp -d -t .mount_missioncontrol_XXXXXX)
trap 'rm -rf "$RUN_DIR"' EXIT INT TERM HUP

# Extract payload into runtime sandbox
SKIP=$(awk '/^__ARCHIVE_MARKER__/ {print NR + 1; exit 0; }' "$0")
tail -n +"$SKIP" "$0" | tar -xz --strip-components=1 -C "$RUN_DIR" 2>/dev/null || tail -n +"$SKIP" "$0" | tar -xz -C "$RUN_DIR"

# Launch Mission Control with forwarded arguments
export APPDIR="$RUN_DIR"
export OWNDIR="$RUN_DIR"
export LD_LIBRARY_PATH="$RUN_DIR:$RUN_DIR/swiftshader:$LD_LIBRARY_PATH"
cd "$RUN_DIR"
chmod +x ./mission-control-frontend ./chrome-sandbox ./chrome_crashpad_handler 2>/dev/null || true

exec "$RUN_DIR/mission-control-frontend" "$@"
exit 0
__ARCHIVE_MARKER__
'''

def pack_appimage(version: str, dist_dir: Path):
    output_appimage = dist_dir / f"MissionControl-Linux-{version}.AppImage"
    existing_tar_gz = dist_dir / f"MissionControl-Linux-{version}.tar.gz"
    linux_unpacked = dist_dir / "linux-unpacked"

    print(f"[AppImage] Generating '{output_appimage.name}' for v{version}...")

    # Strategy A: Use pre-existing tar.gz built by electron-builder
    if existing_tar_gz.exists() and existing_tar_gz.stat().st_size > 1024 * 1024:
        print(f"[AppImage] Fast-packaging using existing archive '{existing_tar_gz.name}'...")
        with open(output_appimage, "wb") as f_out:
            f_out.write(RUNNER_SCRIPT)
            with open(existing_tar_gz, "rb") as f_tar:
                while chunk := f_tar.read(4 * 1024 * 1024):
                    f_out.write(chunk)
    # Strategy B: Use native system tar on linux-unpacked
    elif linux_unpacked.exists():
        print(f"[AppImage] Creating archive from '{linux_unpacked}' using system tar...")
        temp_tar = dist_dir / f"temp_appimage_{version}.tar.gz"
        try:
            cmd = ["tar", "-czf", str(temp_tar), "-C", str(dist_dir), "linux-unpacked"]
            subprocess.run(cmd, check=True)
            with open(output_appimage, "wb") as f_out:
                f_out.write(RUNNER_SCRIPT)
                with open(temp_tar, "rb") as f_tar:
                    while chunk := f_tar.read(4 * 1024 * 1024):
                        f_out.write(chunk)
        finally:
            if temp_tar.exists():
                temp_tar.unlink()
    else:
        raise FileNotFoundError(f"Neither '{existing_tar_gz}' nor '{linux_unpacked}' found in {dist_dir}")

    size_mb = output_appimage.stat().st_size / (1024 * 1024)
    print(f"[SUCCESS] Universal AppImage created at: {output_appimage} ({size_mb:.1f} MB)")
    return output_appimage

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python pack_appimage.py <version>")
        sys.exit(1)

    version_arg = sys.argv[1].lstrip('v')
    script_dir = Path(__file__).resolve().parent
    dist_directory = script_dir.parent / "frontend" / "out" / "dist"

    pack_appimage(version_arg, dist_directory)
