"""
Voice Macro Engine — Maps voice commands to in-game key sequences.

Supports built-in macros and user-defined custom macros loaded from config.
Uses fuzzy substring matching to tolerate speech recognition imprecision.
"""

import logging
import time
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


class VoiceMacroEngine:
    """
    Maps voice trigger phrases to key sequences that can be executed
    via InputManager when agentic mode is active.
    """

    # Minimum similarity threshold for fuzzy matching (0.0 - 1.0)
    MATCH_THRESHOLD = 0.6

    def __init__(self, config: Optional[dict] = None):
        self.config = config or {}
        self._macros: Dict[str, List[str]] = {}
        self._key_delay: float = 0.05  # Delay between sequential key presses
        self.refresh_game_macros()

    def refresh_game_macros(self):
        """Update macros from the active game's keybinding profile.

        Layer order (lowest priority → highest priority):
          1. Dynamic profile  — auto-generated by LLM or parsed from game
                                config files.  This is the base layer.
          2. User overrides   — bindings the user has remapped in-game,
                                propagated via apply_user_overrides().
          3. Custom macros    — explicit entries in config["voice"]["custom_macros"].
                                These always win, allowing the user to bind
                                natural-language phrases to any key they want.

        By building the base first and applying user changes on top, a user
        who rebinds "Sprint" from Shift to CapsLock will automatically have
        the voice command "sprint" mapped to CapsLock without any manual edit.
        """
        from ai_brain.game_knowledge import get_knowledge_base

        self._macros = {}

        kb = get_knowledge_base()
        active_game = kb.active_game

        def clean_key(key_str: str) -> str:
            """Normalise a raw key string to a pynput-compatible name."""
            k = key_str.lower().strip()
            # Strip " (user-set)" annotation if present
            k = k.replace(" (user-set)", "").replace(" (user-configured)", "")
            if "lmb" in k or "left mouse" in k: return "lmb"
            if "rmb" in k or "right mouse" in k: return "rmb"
            if "space" in k: return "space"
            if "shift" in k: return "shift"
            if "ctrl" in k: return "ctrl"
            if "escape" in k or "esc" in k: return "escape"
            if "tab" in k: return "tab"
            if "enter" in k: return "enter"
            parts = k.replace("(", "").replace(")", "").split()
            if parts:
                if parts[0] == "l-shift": return "shift"
                if parts[0] == "l-ctrl": return "ctrl"
                return parts[0]
            return k

        def load_keybinds_from_dict(keybinds: dict, overwrite: bool = False):
            """Populate self._macros from a category→{label: key} dict.

            If overwrite=True, existing entries are replaced (used for the
            user-override and custom-macro layers).
            """
            for category, bindings in keybinds.items():
                if not isinstance(bindings, dict):
                    continue
                for label, key_str in bindings.items():
                    if not isinstance(key_str, str):
                        continue
                    triggers = [t.strip().lower() for t in label.split("/")]
                    # Skip analogue / controller-only bindings
                    if any(skip in key_str for skip in
                           ("W A S D", "L-Stick", "R-Stick", "Mouse Wheel",
                            "D-Pad", "Analog")):
                        continue
                    parsed_key = clean_key(key_str.split("|")[0])
                    for t in triggers:
                        if overwrite or t not in self._macros:
                            self._macros[t] = [parsed_key]

        # ── Layer 1: Dynamic profile (base) ─────────────────────────────────
        if active_game:
            profile = kb.get_dynamic_profile(active_game)
            if profile and profile.keybinds:
                load_keybinds_from_dict(profile.keybinds, overwrite=False)
                logger.debug(
                    f"[VoiceMacro] Base keybinds loaded for '{active_game}' "
                    f"(source={profile.source}): {len(self._macros)} entries."
                )

                # ── Layer 2: User overrides (in-game remapped keys) ──────────
                if profile.user_overrides:
                    for action, key_str in profile.user_overrides.items():
                        trigger = action.lower()
                        parsed = clean_key(key_str)
                        self._macros[trigger] = [parsed]
                    logger.debug(
                        f"[VoiceMacro] Applied {len(profile.user_overrides)} user overrides."
                    )
            elif active_game:
                logger.debug(
                    f"[VoiceMacro] No profile yet for '{active_game}' — "
                    f"generation may be in-flight."
                )

        # ── Layer 3: Config custom macros (explicit user additions) ──────────
        custom_macros = self.config.get("voice", {}).get("custom_macros", {})
        if isinstance(custom_macros, dict) and custom_macros:
            for trigger, keys in custom_macros.items():
                if isinstance(keys, list):
                    self._macros[trigger.lower()] = keys   # always overwrite
                elif isinstance(keys, str):
                    self._macros[trigger.lower()] = [keys]
            logger.debug(
                f"[VoiceMacro] Merged {len(custom_macros)} custom macro entries."
            )

    def match_macro(self, text: str) -> Optional[str]:
        """
        Find the best matching macro for the given voice text.
        Returns the macro trigger phrase if a match is found, None otherwise.
        Uses substring matching with similarity scoring.
        """
        if not text:
            return None

        # Refresh macros in case the active game changed
        self.refresh_game_macros()

        text_lower = text.lower().strip()

        # 1. Exact match
        if text_lower in self._macros:
            return text_lower

        # 2. Substring containment (e.g., "hey quick save please" → "quick save")
        best_match = None
        best_length = 0
        for trigger in self._macros:
            if trigger in text_lower:
                # Prefer the longest matching trigger to avoid ambiguity
                if len(trigger) > best_length:
                    best_match = trigger
                    best_length = len(trigger)

        if best_match:
            return best_match

        # 3. Fuzzy word overlap matching
        text_words = set(text_lower.split())
        best_score = 0.0
        best_fuzzy = None

        for trigger in self._macros:
            trigger_words = set(trigger.split())
            if not trigger_words:
                continue
            overlap = len(text_words & trigger_words)
            score = overlap / len(trigger_words)
            if score > best_score and score >= self.MATCH_THRESHOLD:
                best_score = score
                best_fuzzy = trigger

        return best_fuzzy

    def execute_macro(self, macro_name: str, input_manager) -> bool:
        """
        Execute a macro by pressing its key sequence through the InputManager.
        Returns True if execution succeeded.
        """
        keys = self._macros.get(macro_name)
        if not keys:
            logger.warning(f"[VoiceMacro] Macro '{macro_name}' not found")
            return False

        logger.info(f"[VoiceMacro] Executing macro '{macro_name}': {keys}")

        try:
            for key in keys:
                input_manager.execute_key(key, mode="click")
                if len(keys) > 1:
                    time.sleep(self._key_delay)

            logger.info(f"[VoiceMacro] Macro '{macro_name}' executed successfully")
            return True
        except Exception as e:
            logger.error(f"[VoiceMacro] Failed to execute macro '{macro_name}': {e}")
            return False

    def list_macros(self) -> Dict[str, List[str]]:
        """Return all available macros (built-in + custom)."""
        return dict(self._macros)

    def add_macro(self, trigger: str, keys: List[str]):
        """Add or update a macro at runtime."""
        self._macros[trigger.lower()] = keys
        logger.info(f"[VoiceMacro] Added/updated macro: '{trigger}' → {keys}")

    def remove_macro(self, trigger: str) -> bool:
        """Remove a macro. Returns True if it existed."""
        key = trigger.lower()
        if key in self._macros:
            del self._macros[key]
            logger.info(f"[VoiceMacro] Removed macro: '{trigger}'")
            return True
        return False
