import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'gamingPost',
  title: 'Gaming Blog Post',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {
        list: [
          { title: 'Game News', value: 'Game News' },
          { title: 'GPU News', value: 'GPU News' },
          { title: 'Game Revisit', value: 'Game Revisit' },
          { title: 'Hardware Deep-Dive', value: 'Hardware Deep-Dive' },
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
      description: 'Short summary shown in blog card previews (max 200 chars).',
    }),
    defineField({
      name: 'mainImage',
      title: 'Main image',
      type: 'image',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'markdownBody',
      title: 'Article Body (Markdown)',
      type: 'text',
      rows: 30,
      description: 'Full article in Markdown format. Supports ## headings, tables, code blocks.',
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'string',
      initialValue: 'Mission Control Intel',
    }),
    defineField({
      name: 'aiGenerated',
      title: 'AI Generated',
      type: 'boolean',
      initialValue: false,
      description: 'Flag set automatically when this post was generated by the AI pipeline.',
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published At',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
    }),
  ],
  preview: {
    select: {
      title: 'title',
      category: 'category',
      aiGenerated: 'aiGenerated',
    },
    prepare({ title, category, aiGenerated }) {
      return {
        title,
        subtitle: `${category ?? 'Uncategorised'}${aiGenerated ? ' • AI' : ''}`,
      }
    },
  },
})
