services:
  distributed_library_server:
    build: .
    container_name: mc-distributed-library-server
    restart: always
    ports:
      - "8800:8800"
    env_file:
      - .env
    volumes:
      - ./queries:/app/queries

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: mc-library-tunnel
    restart: always
    command: tunnel --url http://distributed_library_server:8800 --no-autoupdate
    depends_on:
      - distributed_library_server

