# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: arnab825.MissionControl
PackageVersion: 3.8.0
InstallerType: nullsoft
Scope: machine
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Commands:
  - MissionControl
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/arnab825/Mission-Control/releases/download/v3.8.0/MissionControl-Setup.exe
    InstallerSha256: 4853046B4313821B2DCFBB68D3DD9A224FB80048213E9AB0B1C2A8400786A9CB
ManifestType: installer
ManifestVersion: 1.6.0
